# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:50
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('SDS', 'SDSLabs'), ('MDG', 'Mobile Development Group'), ('IARC', 'IARC'), ('GG', 'Geek Gazette'), ('WONA', 'Watch Out News Agency')], max_length=4, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='CompAlum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.TextField(max_length=25, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='UnivAlum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.TextField(max_length=25, verbose_name='Universities')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users')),
                ('dob', models.DateTimeField(verbose_name='Date Of Birth')),
                ('batch', core.models.YearField(verbose_name='Batch')),
                ('branch', models.CharField(choices=[('BT', 'Biotechnology'), ('AR', 'Architecture and Planning'), ('CH', 'Chemical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('IN', 'Production and Industrial'), ('MT', 'Metallurgical and Materials Engineering'), ('PP', 'Pulp and Paper Engineering'), ('PS', 'Polymer and Process Engineering'), ('EPH', 'Engineering Physics'), ('MSM', 'Applied Mathematics'), ('GT', 'Geological Technology'), ('GPT', 'Geophysical Technology'), ('PHD', 'PHD'), ('PBT', 'PHD Biotechnology')], max_length=3, verbose_name='Branch')),
                ('interest', models.TextField(max_length=250, verbose_name='Interest')),
                ('alumni_card', models.BooleanField(default='false', verbose_name='Alumni Card')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='user',
            field=models.ManyToManyField(through='core.UnivAlum', to='core.User'),
        ),
        migrations.AddField(
            model_name='univalum',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University'),
        ),
        migrations.AddField(
            model_name='univalum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ManyToManyField(to='core.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(through='core.CompAlum', to='core.User'),
        ),
        migrations.AddField(
            model_name='compalum',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
        migrations.AddField(
            model_name='compalum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='campusgroup',
            name='user',
            field=models.ManyToManyField(to='core.User'),
        ),
    ]
