# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('SDS', 'SDSLabs'), ('MDG', 'Mobile Development Group'), ('IARC', 'IARC'), ('GG', 'Geek Gazette'), ('WONA', 'Watch Out News Agency')], max_length=4, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='CompAlum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Company Name')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('enr_no', models.IntegerField(null=True, verbose_name='Enrollment Number')),
                ('batch', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='Batch')),
                ('degree_photo', models.ImageField(upload_to='degree_photo')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnivAlum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.TextField(max_length=25, verbose_name='Universities')),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('enr_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('batch', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='Batch')),
                ('branch', models.CharField(choices=[('BT', 'Biotechnology'), ('AR', 'Architecture and Planning'), ('CH', 'Chemical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('IN', 'Production and Industrial'), ('MT', 'Metallurgical and Materials Engineering'), ('PP', 'Pulp and Paper Engineering'), ('PS', 'Polymer and Process Engineering'), ('EPH', 'Engineering Physics'), ('MSM', 'Applied Mathematics'), ('GT', 'Geological Technology'), ('GPT', 'Geophysical Technology'), ('PHD', 'PHD'), ('PBT', 'PHD Biotechnology')], max_length=3, verbose_name='Branch')),
                ('interest', models.TextField(blank=True, max_length=250, null=True, verbose_name='Interest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alum',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alum', serialize=False, to='core.User', verbose_name='Alumni')),
                ('alumni_card', models.BooleanField(default='false', verbose_name='Alumni Card')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to='core.User', verbose_name='Student')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='campus_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.CampusGroup'),
        ),
        migrations.AddField(
            model_name='univalum',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University'),
        ),
        migrations.AddField(
            model_name='compalum',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
        migrations.AddField(
            model_name='univalum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Alum'),
        ),
        migrations.AddField(
            model_name='compalum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Alum'),
        ),
        migrations.AddField(
            model_name='alum',
            name='companies',
            field=models.ManyToManyField(related_name='alums', through='core.CompAlum', to='core.Company'),
        ),
        migrations.AddField(
            model_name='alum',
            name='locations',
            field=models.ManyToManyField(related_name='alums', to='core.Location'),
        ),
        migrations.AddField(
            model_name='alum',
            name='universities',
            field=models.ManyToManyField(related_name='alums', through='core.UnivAlum', to='core.University'),
        ),
    ]
