# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_location_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PHD', 'PHD')], max_length=7, verbose_name='Course'),
        ),
    ]
