# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180228_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_alumni',
        ),
    ]
