# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_is_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='Official Email Address'),
        ),
    ]
