# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180316_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Joining'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leaving_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Leaving'),
        ),
    ]
