# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180316_0255'),
        ('core', '0006_auto_20180316_0029'),
    ]

    operations = [
    ]
