# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 23:42
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180316_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', ckeditor.fields.RichTextField(default='')),
                ('include_name', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscriber', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Subscriber')),
                ('is_subscribed', models.BooleanField(default=True)),
                ('subscription_key', models.CharField(blank=True, max_length=32, unique=True)),
            ],
        ),
    ]
