# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailmessage_subscriber'),
        ('core', '0009_merge_20180316_0451'),
    ]

    operations = [
    ]
