# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 20:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20180318_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_subscribed', models.BooleanField(default=True)),
                ('subscription_key', models.CharField(blank=True, max_length=32, unique=True)),
            ],
        ),
    ]
