# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20180117_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=60, verbose_name='Course Name')),
                ('duration', models.CharField(max_length=50, verbose_name='Course Duration')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='Event Details')),
                ('link', models.URLField(verbose_name='External links')),
                ('venue', models.CharField(blank=True, default=None, max_length=100)),
                ('date', models.DateTimeField(default=None, verbose_name='Event Date')),
                ('coverImage', models.ImageField(default=None, upload_to='img/events', verbose_name='Cover Image of Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default=None, upload_to=website.models.event_image_directory_path, verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Small Description of Image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default=None)),
                ('image', models.ImageField(default='None', upload_to='img/headlines')),
                ('link', models.URLField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None, verbose_name='Small Description of Initiative')),
            ],
        ),
        migrations.CreateModel(
            name='KnowYourAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default=None, verbose_name='External Link')),
                ('description', models.TextField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact_no', models.CharField(max_length=15)),
                ('batch_of', models.PositiveIntegerField(default=None)),
                ('branch', models.CharField(default=None, max_length=40)),
                ('role', models.CharField(max_length=20)),
                ('link', models.URLField(verbose_name='Link to Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Mou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='University Name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('letter', models.FileField(default=None, upload_to='mou/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='NewsLetter Title')),
                ('content', models.TextField(verbose_name='NewsLetter Content')),
                ('external_link', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='Published on')),
                ('image', models.ImageField(default=None, upload_to='img/newsletter/', verbose_name='NewsLetter Image')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('visibility', models.BooleanField(default=True)),
                ('external_url', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='website.Node')),
            ],
        ),
        migrations.CreateModel(
            name='ShareYourStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='Story Title')),
                ('description', models.TextField(default=None)),
                ('link', models.URLField(default=None, verbose_name='Article Link')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Team name')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Video Title')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Video Description')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=website.models.initiative_image_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='VideoRepository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.VideoRepository'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='website.Team'),
        ),
        migrations.AddField(
            model_name='course',
            name='mou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='website.Mou'),
        ),
    ]
