# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBatchAlumniCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('office_add', models.CharField(default=None, max_length=500, verbose_name='current office address')),
                ('residence_add', models.CharField(default=None, max_length=500, verbose_name='current residence address')),
                ('delivery_add', models.CharField(default=None, max_length=500, verbose_name='current delivery address')),
                ('address', models.CharField(default=None, max_length=500)),
                ('photo', models.ImageField(upload_to=website.models.get_file_path)),
                ('photo_sign', models.ImageField(upload_to=website.models.get_file_path)),
                ('photo_degree', models.ImageField(upload_to=website.models.get_file_path)),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('dob', models.DateField(default=None)),
                ('degree_name', models.CharField(default=None, max_length=255)),
                ('degree_branch', models.CharField(default=None, max_length=255)),
                ('degree_year', models.IntegerField(default=None)),
                ('present_desig', models.CharField(default=None, max_length=255)),
                ('present_dept', models.CharField(default=None, max_length=255)),
                ('telephone', models.CharField(blank=True, default=None, max_length=20)),
                ('mobile', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address_for_correspondence', models.CharField(choices=[('Office Address', 'Office Address'), ('Residence Address', 'Residence Address')], default='Office Address', max_length=50)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='currentAlumniCard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
