# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(choices=[('Golden', 'Golden Jublee'), ('Silver', 'Silver Jublee'), ('Ruby', 'Ruby Jublee'), ('Meet', 'Alumni meet')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='Alumni Meet', max_length=20, verbose_name='Alumni Meet type'),
        ),
    ]
