# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 19:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyouralumni',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='shareyourstory',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
