# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180211_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='mainPage',
            field=models.BooleanField(default=False),
        ),
    ]
