# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180314_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Golden', 'Golden Jublee'), ('Silver', 'Silver Jublee'), ('Ruby', 'Ruby Jublee'), ('Meet', 'Alumni meet')], default=None, max_length=20),
        ),
    ]
