# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_auto_20180314_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareyourstory',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='img/ShareYourStory', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='shareyourstory',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shareYourStory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowyouralumni',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='img/KnowYourAlum', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='knowyouralumni',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='knowYourAlum', to=settings.AUTH_USER_MODEL),
        ),
    ]
