# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180314_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('link', models.URLField(default=None, verbose_name='External Link')),
            ],
        ),
    ]
