# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180316_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('description', models.TextField(default=None)),
                ('link', models.URLField(default=None, verbose_name='External Link')),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
