# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180316_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('GL', 'Guest Lecture'), ('RU', 'Re-Union'), ('AM', 'Alumni meet')], default=None, max_length=20),
        ),
    ]
