# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_auto_20180318_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyouralumni',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='knowYourAlum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareyourstory',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shareYourStory', to=settings.AUTH_USER_MODEL),
        ),
    ]
