# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180318_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowyouralumni',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shareyourstory',
            name='user',
        ),
    ]
