# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_auto_20180318_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnicard',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='alumnicard',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumnicard',
            name='delivery_add',
            field=models.CharField(default=None, max_length=500, verbose_name='current delivery address'),
        ),
        migrations.AddField(
            model_name='alumnicard',
            name='office_add',
            field=models.CharField(default=None, max_length=500, verbose_name='current office address'),
        ),
        migrations.AddField(
            model_name='alumnicard',
            name='residence_add',
            field=models.CharField(default=None, max_length=500, verbose_name='current residence address'),
        ),
        migrations.AddField(
            model_name='knowyouralumni',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='knowYourAlum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareyourstory',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shareYourStory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumnicard',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alumniCard', to=settings.AUTH_USER_MODEL),
        ),
    ]
