# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180319_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyouralumni',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='knowYourAlum', to=settings.AUTH_USER_MODEL),
        ),
    ]
