# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20180329_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyouralumni',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
