# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20180329_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyouralumni',
            name='link',
            field=models.URLField(default=None, null=True, verbose_name='External Link'),
        ),
    ]
