# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20180329_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyouralumni',
            name='link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='External Link'),
        ),
        migrations.AlterField(
            model_name='shareyourstory',
            name='link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Article Link'),
        ),
        migrations.AlterField(
            model_name='shareyourstory',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Story Title'),
        ),
    ]
